[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmds = ["python app.py"] 
# Ou o comando que vocÃª usa, ex: "gunicorn app:app"
